export const GET_CURRENT_USER_BEGIN = "BEGIN_USER_CHECK"
export const GET_CURRENT_USER_SUCCESS = "SUCCESS_USER_CHECK"
export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const LOGOUT_USER = "LOGOUT_USER"

export const GET_COLLECTIONS_BEGIN = "GET_COLLECTIONS_BEGIN"
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS"

export const CLEAR_STATS = "CLEAR_STATS"

export const GET_STATS_BEGIN = "GET_STATS_BEGIN"
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS"

export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS"
export const ADD_COLLECTION_BEGIN = "ADD_COLLECTION_BEGIN"
export const ADD_COLLECTION_ERROR = "ADD_COLLECTION_ERROR"

export const ADD_URL_BEGIN = "ADD_URL_BEGIN"
export const ADD_URL_SUCCESS = "ADD_URL_SUCCESS"
export const ADD_URL_ERROR = "ADD_URL_ERROR"